### ISSUE TITLE
rpc player is visible in MineClone2

### ISSUE THREAD

**Issue by EliasFleckenstein03** [HimbeerserverDE/multiserver_api#1]
The reason for this is that gamemods are run after normal mods. That way multiserver initalizes rpc to be invisible, but then mcl_player initalizes rpc like a normal player.
![screenshot_20210219_164325](https://user-images.githubusercontent.com/54945686/108525574-854b4a00-72d0-11eb-9d8a-42da238a0f09.png)

**Comment by HimbeerserverDE** [comment]
This should be fixed now
